== Git Caching Strategy Plugin
This plugin is under development.

==== Build

To build the plugin locally:

[source,shell]
----
mvn clean verify
----

==== Test local instance

To test in a local Jenkins instance

[source,shell]
----
mvn hpi:run
----


This plugin is under development.

To run this plugin checkout my fork of git plugin (CachingStrategy.java is an extension point created) and git caching strategy
into your workspace, perform mvn clean install on both and mvh hpi:run on git caching strategy.

Due to the complexity of UI and not much understanding, my Initial implementation considers a list of cacheStrategies as a property 
of GitSCM class, then upon further analysis I felt it to be misplaced and found it fit's perfectly GitSCMSource's property so that each
instance of GitSCM can be injected these property via AbstractGITSCMBuilder, this was requiring alot of modifications on existing codebase
at the same I also had a thought of integrating the functionality as additional behaviours and now with basic understanding of UI, I tried to implementing
it as part GitExtensions, (this right now seems the best choice) as the whole point of extension points are to tweak
the behaviour of GitSCM.

Current status: It is able to perform a git clone at a specific locations
